[package]
name = "solutiont5"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"

[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

[[test]]
name = "tests"
path = "src/tests.rs"
